### ISSUE TITLE
Possible threading issue

### ISSUE THREAD

**Issue by jbourassa** [jim/carmen#179]
I've had strange issues with my logs so I'm wondering if Carmen is known to be thread safe?

My symptom is that, in my web server (Puma), running `Carmen::Country.coded` will sometimes return `nil` for a country code that exists. Calling the same function with same arguments outside my web process finds a `Country`, as expected.

Digging through the source, everything looks fine so I'm kinda confused at what might be happening. Any pointers appreciated.

**Comment by j15e** [comment]
@jbourassa I found our issue, it is not thread related but because we modify the array of countries without cloning it and it isn't frozen.

Example :

```ruby
Carmen::Country.all.size 
# => 248

limited_countries = ['CA']
available_countries = Carmen::Country.all
available_countries.select! { |c| limited_countries.include?(c.code) } if limited_countries

Carmen::Country.all.size
# => 1

Carmen::Country.coded('US')
# => nil
```

To prevent creating this issue I think the regions could be freeze once they are loaded here (or simply not use `select!` like I did) ; https://github.com/jim/carmen/blob/master/lib/carmen/region.rb#L24

**Comment by jbourassa** [comment]
Awesome, sorry for the trouble.

**Comment by CDainMiller** [comment]
@j15e Thanks for the assist, we will consider freezing that for sure. Let us know if you see anything else that is odd @jbourassa!
