### ISSUE TITLE
Idea for Carmen from SciRuby

### ISSUE THREAD

**Issue by dainmiller** [jim/carmen#190]
A few of the folks over at [SciRuby](http://sciruby.com/) are interested in more data normalization and generation gems. And they thought Carmen could fill an interesting role there. They are trying to mature to match the SciPy stack.

Carmen could effectively be the go-to library for any geographic data science in Ruby.

But it'd expand on the functionality greatly, and perhaps should be another gem altogether. A lot of the users of current Carmen distros wouldn't need that data science specific functionality (large data set generation, geographical data pulling and normalization, etc)

Thoughts?

**Comment by j15e** [comment]
Hi, I am not sure to understand exactly what you would like Carmen to evolve into.

I think ideally the data itself should be synced from an already ISO standard source rather than being maintain by the ruby/gem/scipy community itself.

In fact I think this gem was first based on the ISO-3166 dataset, scraped from the debian source, but was not updated automatically after but rather from individual pull requests (which to me seems very prone to errors VS an ISO validated data source).

https://github.com/jim/carmen/blob/master/script/update_data.rb#L61-L62

I think if you plan into adding much more functionality, you'd be better off a fresh start. The greatest quality of this gem is that the dataset was quite well maintained, but it was done manually, and the code itself was created more than 5 years ago.

**Comment by dainmiller** [comment]
@j15e Good points, I tend to agree. It makes more sense to fork into its own gem for SciRuby and go from there since this one has such a focused set of functionality.
