### ISSUE TITLE
typed doesn't exist

### ISSUE THREAD

**Issue by ajbeach2** [jim/carmen#205]
typed method doesn't exist. The example in the readme is broken

```ruby
2.3.0 :028 > us = Country.named('United States')
 => <#Carmen::Country name="United States"> 
2.3.0 :029 > states = us.subregions.typed('state')
NoMethodError: undefined method `typed' for #<Carmen::RegionCollection:0x007fd3855325b8>
	from (irb):29
	from /Users/abeach/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
2.3.0 :030 > 
```

**Comment by chrisdpeters** [comment]
@ajbeach2 `#typed` does in fact exist in `master`. Are you trying to reference it in v1.0.2 of the gem? If so, that's why you're receiving an error that it's not there.

See [the 1.0.2 tag](https://github.com/jim/carmen/tree/ac128ac12aa148c2be8d5587215b3554c9cbda6c) for details about what's available in that version.

**Comment by jim** [comment]
This will be resolved with the next released version. In the mean time, you can use master.
