### ISSUE TITLE
Allow more granular datasets

### ISSUE THREAD

**Issue by jim** [jim/carmen#43]
Right now Carmen can only support countries and a single level of child states. There are places in the world where this 2-level design doesn't really work.

Version 2 should have a refined API that can handle a variable number of levels, as well as a data format that is flexible enough to store this data.

**Comment by jim** [comment]
Closing this since there hasn't been any activity on it in 2 years.

**Comment by sesam** [comment]
Sad to see. I'd be interested in pushing this forward, but not sure what to do? Maybe help on the debian import code?

**Comment by CDainMiller** [comment]
@triemstr open a new issue with your latest comment if it's still something you'd like to see.

@sesam It seems the spree community or integration idea at the top of this thread is a good one, but I disagree with @triemstr that we should combine those methodologies. They are using database tables whereas we are using in memory objects basically and I think they each have pros and cons but need'nt be done the same way just for convenience. I think we could benefit by it, but idk. Im not sold. As far as what this means for the nesting levels and granular datasets, we will need to refactor our method for handling that entirely - if we do in fact want more granular data sets.

So, yeah, if you want to push this forward then you could open a new issue that has a brief summary of what you want to add then links to this closed thread for reference. Then we can begin having a conversation as to what exactly we need to refactor to accomplish this. Let's just do it in a new issue as this one is super old.

**Comment by sesam** [comment]
Tnx, nicely summed up. At some point I'll need to connect data on even down to municipality- level, but no hurry. Will keep this marked until next time.

**Comment by CDainMiller** [comment]
Awesome. Thanks!

**Comment by triemstr** [comment]
@CDainMiller Thanks for the update. I no longer use this gem, but the original intention was just a DRY thought since I had to use 3 gems with different datasets to get what I needed accomplished. Each gem had its advantages...but each gem had different datasets once you get down to the region/state/province level and some did better than others to be written in the native language of that country. 

Carmen was the one that was best to serve the community at that time and may still be. Other gems like spree or snail could get rid of their own datasets as carmen became the go-to dataset. It would increase the users and maintainers of carmen and increase the value of spree if it was more useful globally. Or that was the thought.

Anyway, good luck. I always really enjoyed this gem.
